decals.wad
gfx/env/fysnowbk.tga
gfx/env/fysnowdn.tga
gfx/env/fysnowft.tga
gfx/env/fysnowlf.tga
gfx/env/fysnowrt.tga
gfx/env/fysnowup.tga
gfx/env/fynitebk.tga
gfx/env/fynitedn.tga
gfx/env/fyniteft.tga
gfx/env/fynitelf.tga
gfx/env/fynitert.tga
gfx/env/fyniteup.tga
ika-icehome.wad
sound/frostline/lase-reload.wav
sound/frostline/mgai-reload.wav
sound/frostline/mgun-reload.wav
sound/frostline/xlai-reload.wav
sound/frostline/ui_shutdown.wav
sound/frostline/ui_start.wav
sound/frostline/ifak_pickup.wav
sound/frostline/item_respawn.wav
models/frostline/npc/agrunt.mdl
models/frostline/npc/agruntf.mdl
models/frostline/npc/babygarg.mdl
models/frostline/npc/babygargf.mdl
models/frostline/npc/barnabus.mdl
models/frostline/npc/barney.mdl
models/frostline/npc/bullsquid.mdl
models/frostline/npc/controller.mdl
models/frostline/npc/gonome.mdl
models/frostline/npc/hgrunt.mdl
models/frostline/npc/hgrunt_opfor.mdl
models/frostline/npc/hgrunt_opforf.mdl
models/frostline/npc/kingpin.mdl
models/frostline/npc/massn.mdl
models/frostline/npc/massnf.mdl
models/frostline/npc/otis.mdl
models/frostline/npc/otisf.mdl
models/frostline/npc/pit_drone.mdl
models/frostline/npc/rgrunt.mdl
models/frostline/npc/rgruntf.mdl
models/frostline/npc/strooper.mdl
models/frostline/npc/Tor.mdl
models/frostline/npc/Torf.mdl
models/frostline/npc/voltigore.mdl
models/frostline/npc/zombie.mdl
models/frostline/npc/zombie_barney.mdl
models/frostline/npc/zombie_soldier.mdl
models/frostline/ws_chemlight.mdl
models/frostline/ws_respack.mdl
sprites/frostline/ws_snow_fx.spr
sprites/frostline/ws_inventory.spr
sprites/frostline/ws_inventory2.spr