// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

gfx/env/maudcloudy_bk.tga
gfx/env/maudcloudy_dn.tga
gfx/env/maudcloudy_ft.tga
gfx/env/maudcloudy_lf.tga
gfx/env/maudcloudy_rt.tga
gfx/env/maudcloudy_up.tga
models/scmod/fracb1/redboots.mdl
models/scmod/item_bluetoolbox.mdl
models/scmod/item_canister.mdl
models/scmod/item_jar.mdl
models/scmod/item_key.mdl
models/scmod/item_robotools.mdl
models/scmod/item_security.mdl
models/scmod/npcs/rgrunt/turrican.mdl
models/scmod/secretcity/kainzombo.mdl
models/scmod/secretcity/p_excalibar.mdl
models/scmod/secretcity/p_minigunidle.mdl
models/scmod/secretcity/p_minigunspin.mdl
models/scmod/secretcity/p_saw.mdl
models/scmod/secretcity/peanydead.mdl
models/scmod/secretcity/peanyzombo.mdl
models/scmod/secretcity/redmetal.mdl
models/scmod/secretcity/shadowchild.mdl
models/scmod/secretcity/shadowslidje.mdl
models/scmod/secretcity/slidjerat.mdl
models/scmod/secretcity/sv_bot.mdl
models/scmod/secretcity/turrican_repaired.mdl
models/scmod/secretcity/v_excalibar.mdl
models/scmod/secretcity/v_minigun.mdl
models/scmod/secretcity/v_saw.mdl
models/scmod/secretcity/v_syringe.mdl
models/scmod/secretcity/vorinc_dead.mdl
models/scmod/secretcity/w_excalibar.mdl
models/scmod/secretcity/w_minigun.mdl
models/scmod/secretcity/w_nukebomb.mdl
models/scmod/secretcity/w_saw.mdl
models/scmod/secretcity/w_saw_clip.mdl
models/scmod/weapons/dmc/b_nail1.mdl
models/scmod/weapons/dmc/light/p_shock.mdl
models/scmod/weapons/dmc/light/v_shock.mdl
models/scmod/weapons/dmc/light/w_shock.mdl
models/scmod/weapons/dmc/light/w_shock_rifle.mdl
models/scmod/weapons/dmc/ngun2/p_9mmar.mdl
models/scmod/weapons/dmc/ngun2/v_9mmar.mdl
models/scmod/weapons/dmc/ngun2/w_9mmar.mdl
models/scmod/weapons/dmc/shot/p_shotgun.mdl
models/scmod/weapons/dmc/shot/v_shotgun.mdl
models/scmod/weapons/dmc/shot/w_shotgun.mdl
models/scmod/weapons/dmc/w_battery.mdl
models/scmod/weapons/dmc/w_shotbox.mdl
models/turr/intruder2.mdl
models/turr/scicotic.mdl
secretcitysaga.wad
sound/scmod/fracb1/dialogs/20turrican.ogg
sound/scmod/fracb1/dialogs/6turrican_r.ogg
sound/scmod/fracb1/dialogs/7turrican_r.ogg
sound/scmod/fracb1/dialogs/8turrican_r.ogg
sound/scmod/fracb1/dialogs/evilturr0.ogg
sound/scmod/fracb1/dialogs/evilturr1.ogg
sound/scmod/fracb1/dialogs/evilturr2.ogg
sound/scmod/fracb1/dialogs/noescape2.ogg
sound/scmod/fracb1/dialogs/turrspeak1.ogg
sound/scmod/fracb1/dialogs/turrspeak2.ogg
sound/scmod/fracb1/dialogs/turrspeak3.ogg
sound/scmod/fracb1/dialogs/turrspeak4.ogg
sound/scmod/fracb1/dialogs/turrspeakbail_r.ogg
sound/scmod/fracb1/dialogs/turrspeakboss_r.ogg
sound/scmod/fracb1/dialogs/turrspeakfinal_r.ogg
sound/scmod/fracb1/dialogs/turrwarning.ogg
sound/scmod/fracb1/eventhorizon_orbital.ogg
sound/scmod/fracb1/slidjeboss.ogg
sound/scmod/fracb1/startquake.ogg
sound/scmod/hdmusic/turhd/riker.ogg
sound/scmod/npcs/turrican/grenade.wav
sound/scmod/npcs/turrican/guncock.wav
sound/scmod/npcs/turrican/spikeburst.wav
sound/tur/creepy1.wav
sound/tur/creepy2.wav
sound/tur/creepy3.wav
sound/tur/creepy4.wav
sound/tur/creepy5.wav
sound/tur/fracture1_loop.ogg
sound/tur/fracture1intense_loop.ogg
sound/tur/fracture3_loop.ogg
sound/tur/fracture4_loop.ogg
sound/weapons/charger7/clipin_1.wav
sound/weapons/charger7/clipin_2.wav
sound/weapons/charger7/clipin_3.wav
sound/weapons/charger7/clipout_1.wav
sound/weapons/charger7/clipout_2.wav
sound/weapons/charger7/draw.wav
sound/weapons/charger7/saw_fire1.wav
sound/weapons/charger7/saw_fire2.wav
sound/weapons/charger7/saw_fire3.wav
sound/weapons/dmc/light/lstart.wav
sound/weapons/dmc/ngun2/spike2.wav
sound/weapons/dmc/shot/guncock.wav
sound/weapons/dmc/weapon.wav
sprites/scmod/item_keycard.spr
