// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

gfx/env/solred_bk.tga
gfx/env/solred_dn.tga
gfx/env/solred_ft.tga
gfx/env/solred_lf.tga
gfx/env/solred_rt.tga
gfx/env/solred_up.tga
models/scmod/reddeath/hopper.mdl
models/scmod/reddeath/nomble.mdl
models/scmod/reddeath/nomblesoft.mdl
models/scmod/reddeath/nuke.mdl
models/scmod/reddeath/shadowchild.mdl
models/scmod/reddeath/turrible.mdl
models/scmod/secretcity/p_excalibar.mdl
models/scmod/secretcity/p_minigunidle.mdl
models/scmod/secretcity/p_minigunspin.mdl
models/scmod/secretcity/p_saw.mdl
models/scmod/secretcity/redmetal.mdl
models/scmod/secretcity/turrican_repaired.mdl
models/scmod/secretcity/v_excalibar.mdl
models/scmod/secretcity/v_minigun.mdl
models/scmod/secretcity/v_saw.mdl
models/scmod/secretcity/v_syringe.mdl
models/scmod/secretcity/w_excalibar.mdl
models/scmod/secretcity/w_minigun.mdl
models/scmod/secretcity/w_nukebomb.mdl
models/scmod/secretcity/w_saw.mdl
models/scmod/secretcity/w_saw_clip.mdl
models/scmod/weapons/dmc/b_nail1.mdl
models/scmod/weapons/dmc/light/p_shock.mdl
models/scmod/weapons/dmc/light/v_shock.mdl
models/scmod/weapons/dmc/light/w_shock.mdl
models/scmod/weapons/dmc/light/w_shock_rifle.mdl
models/scmod/weapons/dmc/ngun2/p_9mmar.mdl
models/scmod/weapons/dmc/ngun2/v_9mmar.mdl
models/scmod/weapons/dmc/ngun2/w_9mmar.mdl
models/scmod/weapons/dmc/shot/p_shotgun.mdl
models/scmod/weapons/dmc/shot/v_shotgun.mdl
models/scmod/weapons/dmc/shot/w_shotgun.mdl
models/scmod/weapons/dmc/w_battery.mdl
models/scmod/weapons/dmc/w_shotbox.mdl
models/turr/intruder2.mdl
secretcitysaga.wad
sound/scmod/hdmusic/turhd/riker.ogg
sound/scmod/npcs/turrican/grenade.wav
sound/scmod/npcs/turrican/guncock.wav
sound/scmod/npcs/turrican/spikeburst.wav
sound/scmod/reddeath/5secs.ogg
sound/scmod/reddeath/credits.ogg
sound/scmod/reddeath/dialogs/evilturr4.ogg
sound/scmod/reddeath/dialogs/radiocreepy.ogg
sound/scmod/reddeath/introsfx.ogg
sound/scmod/reddeath/lairstart.ogg
sound/scmod/reddeath/nombleboss.ogg
sound/scmod/reddeath/nombleboss_intro.ogg
sound/scmod/reddeath/nukeactivate.ogg
sound/scmod/reddeath/nukeexplosion.ogg
sound/scmod/reddeath/nukeintro.ogg
sound/scmod/reddeath/nukesystems.ogg
sound/scmod/reddeath/shadowsattack.ogg
sound/scmod/reddeath/shipcrash.ogg
sound/scmod/reddeath/tiktok2.ogg
sound/scmod/reddeath/turriblefight.ogg
sound/scmod/reddeath/turriblefight_intro.ogg
sound/tur/creepy1.wav
sound/tur/creepy2.wav
sound/tur/creepy3.wav
sound/tur/creepy4.wav
sound/tur/creepy5.wav
sound/weapons/charger7/clipin_1.wav
sound/weapons/charger7/clipin_2.wav
sound/weapons/charger7/clipin_3.wav
sound/weapons/charger7/clipout_1.wav
sound/weapons/charger7/clipout_2.wav
sound/weapons/charger7/draw.wav
sound/weapons/charger7/saw_fire1.wav
sound/weapons/charger7/saw_fire2.wav
sound/weapons/charger7/saw_fire3.wav
sound/weapons/dmc/light/lstart.wav
sound/weapons/dmc/ngun2/spike2.wav
sound/weapons/dmc/shot/guncock.wav
sound/weapons/dmc/weapon.wav
