// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/ginsmodels/lag_palm240_256.mdl
models/ssa/p_357-v2.mdl
models/ssa/p_9mmar-v2.mdl
models/ssa/p_knife.mdl
models/ssa/p_rpg.mdl
models/ssa/p_s2gl.mdl
models/ssa/p_shotgun.mdl
models/ssa/p_suzi.mdl
models/ssa/p_suzis-dual.mdl
models/ssa/torch.mdl
models/ssa/v_357-v2.mdl
models/ssa/v_9mmar-v2.mdl
models/ssa/v_knife.mdl
models/ssa/v_rpg.mdl
models/ssa/v_s2gl.mdl
models/ssa/v_shotgun-v2.mdl
models/ssa/v_suzi.mdl
models/ssa/w_357-v2.mdl
models/ssa/w_9mmar-v2.mdl
models/ssa/w_knife.mdl
models/ssa/w_rpg.mdl
models/ssa/w_s2gl.mdl
models/ssa/w_shotgun.mdl
models/ssa/w_suzi.mdl
models/ssa/v_mfh-suzi.mdl
models/ssa/w_suzis-dual.mdl
sound/srsam_alpha/doorstonemove.wav
sound/srsam_alpha/doorstonestop.wav
sound/srsam_alpha/egyptkarnakfight.mp3
sound/srsam_alpha/egyptkarnakpeace.mp3
sound/srsam_alpha/info.wav
sound/srsam_alpha/key.wav
sound/srsam_alpha/weps/colt-r1.wav
sound/srsam_alpha/weps/colt-r2.wav
sound/srsam_alpha/weps/colt-r3.wav
sound/srsam_alpha/weps/colt-r4.wav
sound/srsam_alpha/weps/colt_draw.wav
sound/srsam_alpha/weps/explode3.wav
sound/srsam_alpha/weps/explode4.wav
sound/srsam_alpha/weps/explode5.wav
sound/srsam_alpha/weps/fire_colt.wav
sound/srsam_alpha/weps/fire_suzi.wav
sound/srsam_alpha/weps/fire_suzi2.wav
sound/srsam_alpha/weps/fire_tm.wav
sound/srsam_alpha/weps/splauncher_bounce.wav
sound/srsam_alpha/weps/splauncher_fire.wav
sound/srsam_alpha/weps/splauncher_impact.wav
sound/srsam_alpha/weps/splauncher_reload.wav
sound/srsam_alpha/weps/spore_ammo.wav
sound/srsam_alpha/weps/spore_hit1.wav
sound/srsam_alpha/weps/spore_hit2.wav
sound/srsam_alpha/weps/spore_hit3.wav
sound/srsam_alpha/weps/tm-r1.wav
sound/srsam_alpha/weps/tm-r2.wav
sound/weapons/RPG_draw.wav
sound/weapons/RPG_fidget.wav
sound/weapons/RPG_reload.wav
sound/weapons/RPG_start.wav
sound/weapons/spas_idle4.wav
srs_sam-alpha-new.wad
